### ISSUE TITLE
2nd header form not handled

### ISSUE THREAD

**Issue by dten** [Roguelazer/rust-syslog-rfc5424#10]
the spec says headers can be of two formats, i'm getting errors when processes use the 2nd format, am i right in thinking this isn't handled?

```
HEADER          = PRI VERSION SP TIMESTAMP SP HOSTNAME
                  SP APP-NAME SP PROCID SP MSGID
```

**Comment by dten** [comment]
uh am i reading this wrong :)? i've some weird messages from somewhere and they don't work :/ hmm

**Comment by dten** [comment]
yea i'm being stupid and these messages are super malformed

**Comment by dten** [comment]
turns out that `hslogger` makes such rubbish messages that it convinced me i must have misunderstood the spec
https://hackage.haskell.org/package/hslogger-1.2.10/docs/src/System-Log-Handler-Syslog.html#SyslogHandler

**Comment by Roguelazer** [comment]
There are a lot of questionably-formatted "syslog" messages out there; this library isn't super-great at following that IETF adage about being generous in what you accept and strict in what you emit. :-/
